version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - worker
    env_file:
      - .env
    volumes:
      - uploads:/tmp/uploads

  redis:
    image: "redis:alpine"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  worker:
    build: .
    command: celery -A job.celery worker --loglevel=info --events --concurrency=5
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - uploads:/tmp/uploads

volumes:
  uploads:
